version: '3'

services:
  gemini-chat-widget:
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - gemini-network-dev

networks:
  gemini-network-dev:
    driver: bridge
